### ISSUE TITLE
syntax highlight returned code block

### ISSUE THREAD

**Issue by conorhastings** [conorhastings/redux-test-recorder#1]

**Comment by conorhastings** [comment]
https://github.com/wooorm/lowlight

**Comment by wooorm** [comment]
:+1: Let me know how implementation goes, happy to help. at-tmcw was also interested in working with it, so just ensure you’re not doing duplicate work :)

**Comment by conorhastings** [comment]
closed here, https://github.com/conorhastings/redux-test-recorder/pull/8 

@wooorm while working through this i ended up just building https://github.com/conorhastings/react-syntax-highlighter , not sure what @tmcw was interested in here, but if you're interested just let me know, i think we're both in DC.

**Comment by wooorm** [comment]
Awesome! And the interest was React syntax highlighting without 'dangerouslysetInnerHTML'!
