### ISSUE TITLE
Support for Jasmine Unit Test with describe() it() syntax ?

### ISSUE THREAD

**Issue by joyfulelement** [conorhastings/redux-test-recorder#32]
Hi, was facinated to see this amazing work for generating test cases automatically. 

I was also wondering if there were any plan to support Jasmine like Unit Test with syntax such as:
`describe('', () => {...});` 
`it('should xxx', () => {...});`

If we were like to contribute, what would be the good starting place for adding this support? Any suggestions or pointers are much appreciated.
Thanks

**Comment by conorhastings** [comment]
hey, if you take a look here - https://github.com/conorhastings/redux-test-recorder/blob/master/src/create-test/mocha.js , you can see the implementation for mocha. You can easier write a custom function like that and pass it in as the testLib argument, or make a pr with that function to give default library support. I'd be happy to walk you through any issues you might run into. Thanks!
