### ISSUE TITLE
Stateless components testing

### ISSUE THREAD

**Issue by Andarist** [conorhastings/redux-test-recorder#33]
Did you maybe have tried to apply similar logic for generating component tests? I imagine that somebody could experiment with such idea using for example HOC TestRecorder.

**Comment by conorhastings** [comment]
I haven't really spent any time looking into this, but it definitely sounds interesting. I would be worried about the clunkiness of needing to wrap components though. I have played around a little bit with react test generation but in a different way, still in very early stages of dev though - https://github.com/conorhastings/react-test-generator
