### ISSUE TITLE
Move React code in a separate project?

### ISSUE THREAD

**Issue by francesco-strazzullo** [conorhastings/redux-test-recorder#34]
Hi, 
I would like to use this project in an Angular2 + Redux application. Do you think it could be a good idea to  remove all of react dependencies and move the react code (needed for the component) in a new project?  I can create a new repository for the ng2 component.

**Comment by conorhastings** [comment]
yeah i'd be amendable to this, I was thinking about doing this, i'll try to get it done by the weekend. I'll likely leave in some of the dev deps on react related things for the demo but that shouldn't effect any production work.

**Comment by francesco-strazzullo** [comment]
Perfect! I'm building a simpler recorder better suited for my project based on your work. I will create a record button button in Angular2 and then I will try to adapt it to work with your library.

**Comment by francesco-strazzullo** [comment]
Hi @conorhastings this (https://github.com/e-xtrategy/redux-simple-test-recorder) is my version of the redux recorder, it's based on your code but it has a simpler interface and a jasmine test builder. I'm currently using it in an Angular2 application and it's working. I've removed all of the react dependencies.

**Comment by conorhastings** [comment]
Looks cool, I've removed the react specific code form this repo besides the demo now.

Would you mind mentioning this repo in that repo, since a lot of the code appears to just be copied over.

**Comment by francesco-strazzullo** [comment]
Obviously, Sorry If I havent't done it already but the README it just a draft for now! I will try to create a talk about redux where I will talk about how to record redux tests. If you want you can be my reviewer.

**Comment by francesco-strazzullo** [comment]
@conorhastings here the new README for the project! https://github.com/e-xtrategy/redux-simple-test-recorder
