### ISSUE TITLE
How to use with huge single state

### ISSUE THREAD

**Issue by pawelchojnacki** [conorhastings/redux-test-recorder#37]
In most of my projects I'm using single `masterReducer` and `masterStore`, making use of multiple `combineReducers`. My substates have several levels of depth and usually contain quite a lot of data (whole JSONs from the backend), and I'd like to use only specific substates for each test. Can I do that with `redux-test-recorder`? `stateKey` seems to be working only one level deep.

Sample reducer:
```
const masterReducer = combineReducers({
  auth,
  api: combineReducers({
    login,
    account,
    filterModel,
    users
  }),
  views: combineReducers({
    progressBar,
    stringDetails,
    stringDetailsHistory,
    review,
    navbar,
    replace
  }),
  uiLocale
})
```

I've prepared a branch with a fix (splitting `stateKey` on `.`, so `stateKey: 'api.login'` would work in my case), but don't know if it's intended use of this feature. Should I make a PR?

**Comment by conorhastings** [comment]
@pawelchojnacki I think that's a good solution, I would accept a pr for that!
