### ISSUE TITLE
Doesn't work with React-Native? "Unknown option: foreign.Children"

### ISSUE THREAD

**Issue by GeoffreyPlitt** [conorhastings/redux-test-recorder#44]
Has anyone used this with React-Native?

We're doing this:

``` javascript
import {applyMiddleware, createStore, compose} from 'redux'
import * as reduxLoop from 'redux-loop'

import middleware from './middleware'
import reducer from './reducer'

import reduxRecord from 'redux-test-recorder'

const record = reduxRecord({reducer})

const enhancer = compose(
  applyMiddleware([record.middleware, ...middleware]),
  reduxLoop.install(),
  global.reduxNativeDevTools ? global.reduxNativeDevTools(/*options*/) : nope => nope,
)

// create the store
const store = createStore(
  reducer,
  null,
  enhancer
)

if (global.reduxNativeDevTools) {
  global.reduxNativeDevTools.updateStore(store);
}

export const recordProps = record.props

export default store;
```

And getting a TransformError in Babel-land of "Unknown option: foreign.Children".

Please advise, thanks.

**Comment by GeoffreyPlitt** [comment]
Follow-up: The error comes at IMPORT-time, it's a Babel compile issue when it tries to import it. Comes up as a RN "red" error screen, saying the problem is in this module's index.js. Did not get a specific line number.

**Comment by conorhastings** [comment]
@GeoffreyPlitt closing as this was neglected at the time (apologies) feel free to reopen and I'd be happy to look into now that i have more time using react native
