### ISSUE TITLE
immutable state

### ISSUE THREAD

**Issue by brandonmp** [conorhastings/redux-test-recorder#46]
My state is mostly Immutable.js `Maps` and `Lists`. Is this a non-starter for this lib? Is that what 'state must be serializable' means?  If so, any workarounds?

My tests are failing with a few diff't errors:

`state.get is not a function`
`state.removeIn is not a function`
and a few `Expected value to be true, Received false`

This library is an amazing idea, hope I can get it working for my projects!

**Comment by brandonmp** [comment]
i think i've finagled a solution. in the outputted test files, i manually change the test to something like this

```

test('REMOTE_NOTE_ADDED (action index 1) should correctly update state', function () {
  var action = actions[1];
  action.prevState.userNotes = Immutable.fromJS(action.prevState.userNotes) 
  var result = reducers(action.prevState, action.action);
  expect(Immutable.fromJS(result).toJS())
    .toEqual(action.nextState);
});
```

on the `action.prevState.userNotes` line, I do this b/c my action handlers expect to receive immutable slices of state. my `state` is a regular `object` at the top level, so i can't do a full `Immutable.fromJS(state)`--just the slices of state that this test cares about.  

not doing this results in errors (eg, `state.get` is not a function)

then, i change the `expect` expression in 2 ways:
1. since the state my `reducer` returns has `immutable` slices, i just convert the entire thing to `immutable`, and then back to JS. this is the easiest way to get a partially `immutable` obj to plain JS afaik.
2. I use `Jest`'s `toEqual()`.  I'm kind of a newb, so I'm not quite sure why, but `==` doesn't correctly identify matching states.  `toEqual()` checks each prop recursively, so I assume that's the reason.  `toEqual()` also provides a nice `diff` if the objects don't match, which is really helpful.

So I'm all set, but interested to hear if anyone has a better idea how to do this!

**Comment by conorhastings** [comment]
hey @brandonmp thanks for the issue, I'll try to take a look some time this weekend and get back to you

**Comment by conorhastings** [comment]
@brandonmp sorry for lack of response, i think your current solutation is the best available, but i'm going to do some refactoring of this project soon and will take this issue into consideration
